avancado/django/3_P_E_Comerce/app/E_Comerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('Profile.urls')),
    path('order/', include('Order.urls')),
    path('', include('Product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

avancado/django/3_P_E_Comerce/app/Order/urls.py
from django.urls import path

from . import views

app_name = 'Order'

urlpatterns = [
    path('pay/<int:pk>', views.Pay.as_view(), name='pay'),
    path('saveorder/', views.SaveOrder.as_view(), name='saveorder'),
    path('list/', views.List.as_view(), name='list'),
    path('detail/<int:pk>', views.Detail.as_view(), name='detail')
]

avancado/django/3_P_E_Comerce/app/Product/urls.py
from django.urls import path

from . import views

app_name = 'Product'

urlpatterns = [
    path('', views.ListProduct.as_view(), name='list'),
    path('<slug>', views.DetailProduct.as_view(), name='detail'),
    path('addtocar/', views.AddToCar.as_view(), name='addtocar'),
    path('removetocar/', views.RemoveToCar.as_view(), name='removetocar'),
    path('car/', views.Car.as_view(), name='car'),
    path('resumetoshoop/', views.ResumeToShoop.as_view(), name='resumetoshoop'),
    path('getproduct/', views.GetProduct.as_view(), name='getproduct')
]

avancado/django/3_P_E_Comerce/app/Profile/urls.py
from django.urls import path

from . import views
app_name = 'Profile'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('update/', views.Update.as_view(), name='update'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout')
]

avancado/django/3_P_E_Comerce/app/Order/models.py
from django.db import models
from django.contrib.auth.models import User

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
                            default="C",
                            max_length=1,
                            choices=(
                                ('A', 'Aprovado'),
                                ('C', 'Criado'),
                                ('R', 'Reprovado'),
                                ('P', 'Pendente'),
                                ('E', 'Enviado'),
                                ('F', 'Finalizado'),
                            )
    )

    def __str__(self) -> str:
        return f'Pedido número: {self.pk}'
    

class ItemOrder(models.Model):
    class Meta:
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Items'
    
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    price_promotional = models.FloatField(default=0)
    amount = models.PositiveIntegerField()
    image = models.CharField(max_length=2000)

    def __str__(self) -> str:
        return f'Item do {self.order}'
    

    

avancado/django/3_P_E_Comerce/app/Order/views.py
from typing import Any
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render, redirect,reverse
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Order, ItemOrder
from Product.models import Variation
from django.contrib import messages
from utils import utils


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args: Any, **kwargs: Any) -> HttpResponse:
        if not self.request.user.is_authenticated:
            return redirect('Profile:create')
        
        return super().dispatch(*args, **kwargs)
    
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        return qs
    

class Pay(DispatchLoginRequiredMixin, DetailView):
    template_name = 'Order/_pay.html'
    model = Order
    pk_url_kwarg = 'pk'
    context_object_name = 'order'


class SaveOrder(View):
    template_name = 'Order/_pay.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(self.request, 'Login necessário')
            return redirect('Profile:create')
        
        if not self.request.session.get('car'):
            messages.error(self.request, 'Carrinho vazio')
            return redirect('Product:list')
        
        car = self.request.session.get('car')
        car_variation_ids = [v for v in car]
        bd_variation = list(Variation.objects.select_related('product').filter(id__in=car_variation_ids))
        
        for variation in bd_variation:
            vid = str(variation.id)
            stock = variation.stock
            qtd_car = car[vid]['amount']            
            price_unt = car[vid]['price_unt']
            price_unt_promo = car[vid]['price_unt_promo']
            
            error_msg_stock = ''

            if stock < qtd_car:
                car[vid]['amount'] = stock
                car[vid]['price_amount'] = stock * price_unt
                car[vid]['price_amount_promo'] = stock * price_unt_promo

                error_msg_stock = 'Estoque insuficiente para alguns '\
                    'produtos do seu carrinho. '\
                    'Reduzimos a quantidade desses produtos. Por favor, '\
                    'verifique quais produtos foram afetados a seguir.'
                
            if error_msg_stock:
                messages.error(self.request, error_msg_stock)
            
                self.request.session.save()
                return redirect('Product:car')
            
            qtd_total_car = utils.cart_total_qtd(car)
            total_car = utils.cart_totals(car)

        order = Order(user=self.request.user, total=total_car, qtd_total = qtd_total_car, status='C')
        order.save()
        ItemOrder.objects.bulk_create(
            [
                ItemOrder(
                    order=order,
                    product=v['product_name'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['price_amount'],
                    price_promotional=v['price_amount_promo'],
                    amount=v['amount'],
                    image=v['image'],
                ) for v in car.values()
            ]
        )

        del self.request.session['car']

        return redirect(reverse('Order:pay', kwargs={'pk':order.pk}))

class Detail(DispatchLoginRequiredMixin,DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'Order/_details.html'
    pk_url_kwarg = 'pk'

class List(DispatchLoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'Order/_list.html'
    paginate_by = 10
    ordering = ['-id']

avancado/django/3_P_E_Comerce/app/templates/partials/_car.html
{% load static %}
{% load _filter %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for linha in car.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %}{{ linha.image }}">
            </td>
            <td>
                <a href="{% url 'Product:detail' linha.slug %}">
                    {{ linha.product_name }}
                </a>

                <a class="ml-3" href="{% url 'Product:removetocar' %}?vid={{ linha.variation_id }}">
                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{ linha.variation_name }}</td>
            <td>
                {{ linha.amount }} x
                {% if linha.price_unt_promo %}
                    {{ linha.price_unt_promo }}
                {% else %}
                    {{ linha.price_unt }}
                {% endif %}
            </td>

            {% if linha.price_amount_promo %}
                <td>{{ linha.price_amount_promo | formact_price }}</td>
            {% else %}
                <td>{{ linha.price_amount | formact_price }}</td>
            {% endif %}

        </tr>
        {% endfor %}


    </table>
</div>

avancado/django/3_P_E_Comerce/app/templates/partials/_footer.html
{% load static %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">E-comerce feito atravéz do Curso de Python Udemy</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Gabriel Nathan</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js'%}"></script>
<script src="{% static 'assets/custom/js/scripts.js'%}"></script>

avancado/django/3_P_E_Comerce/app/templates/partials/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css'%}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css'%}">

avancado/django/3_P_E_Comerce/app/templates/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

avancado/django/3_P_E_Comerce/app/templates/partials/_nav.html
{% load _filter %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'Product:list' %}">E-commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Conta
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'Order:list' %}">Meus pedidos</a>
                    <a class="dropdown-item" href="{% url 'Profile:create' %}">Atualizar meus dados</a>
                    <a class="dropdown-item" href="{% url 'Profile:logout' %}">Sair</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Profile:create' %}">Entrar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Profile:create' %}">Criar conta</a>
            </li>
            {% endif %}

            {% if request.session.car %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url 'Product:car' %}">
                    <span class="nav-cart-text mr-1">
                        Carrinho
                    </span>
                    <span class="nav-cart-count mr-1">
                        <strong>{{ request.session.car |cart_total_qtd }}x</strong>
                    </span>
                    <span class="nav-cart-icon mr-2">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                </a>
            </li>
            {% endif %}


        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'Product:getproduct' %}">
            <input name="termo" value="{{ request.GET.termo }}" class="form-control mr-sm-2" type="search"
                placeholder="Busca" aria-label="Busca">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Busca</button>
        </form>
    </div>
</nav>

avancado/django/3_P_E_Comerce/app/templates/partials/_order.html
{% load static %}
{% load _filter %}

<div class="row">
    <div class="col">
        <h3>{{ order }}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ order.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ order.total | formact_price }}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{ order.qtd_total }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ order.get_status_display }}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>

                {% for linha in order.itemorder_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{ linha.image }}">
                    </td>
                    <td>{{ linha.product }}</td>
                    <td>{{ linha.variation }}</td>
                    <td>{{ linha.amount}}</td>
                    <td>
                        {% if linha.price_promotion %}
                            {{ linha.price_promotion | formact_price }}
                        {% else %}
                            {{ linha.price | formact_price }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

avancado/django/3_P_E_Comerce/app/templates/partials/_pagination.html
{% if is_paginated %}

<div class="col mt-3 mb-3">
    <div class="row">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}