avancado/django/3_P_E_Comerce/app/E_Comerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('Profile.urls')),
    path('order/', include('Order.urls')),
    path('', include('Product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

avancado/django/3_P_E_Comerce/app/Order/urls.py
from django.urls import path

from . import views

app_name = 'Order'

urlpatterns = [
    path('pay/<int:pk>', views.Pay.as_view(), name='pay'),
    path('saveorder/', views.SaveOrder.as_view(), name='saveorder'),
    path('list/', views.List.as_view(), name='list'),
    path('detail/<int:pk>', views.Detail.as_view(), name='detail')
]

avancado/django/3_P_E_Comerce/app/Product/urls.py
from django.urls import path

from . import views

app_name = 'Product'

urlpatterns = [
    path('', views.ListProduct.as_view(), name='list'),
    path('<slug>', views.DetailProduct.as_view(), name='detail'),
    path('addtocar/', views.AddToCar.as_view(), name='addtocar'),
    path('removetocar/', views.RemoveToCar.as_view(), name='removetocar'),
    path('car/', views.Car.as_view(), name='car'),
    path('resumetoshoop/', views.ResumeToShoop.as_view(), name='resumetoshoop'),
    path('getproduct/', views.GetProduct.as_view(), name='getproduct')
]

avancado/django/3_P_E_Comerce/app/Profile/urls.py
from django.urls import path

from . import views
app_name = 'Profile'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('update/', views.Update.as_view(), name='update'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout')
]

avancado/django/3_P_E_Comerce/app/Product/models.py
from django.conf import settings
from django.db import models
import os
from PIL import Image
from django.db import models
from django.utils.text import slugify
from utils import utils

class Product(models.Model):
    name = models.CharField(max_length=255)
    description_short = models.TextField(max_length=255)
    description_long = models.TextField()
    image = models.ImageField(upload_to='product_images/%Y/%m/', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    price_marketing = models.FloatField(verbose_name='Price')
    price_marketing_promotion = models.FloatField(default=0, verbose_name='Price Promo. ')
    _type = models.CharField(default='V', max_length=1, choices=(('V', 'Variável'),('S', 'Simples'),))


    def get_price_formact(self):
        return utils.formact_price(self.price_marketing)
    get_price_formact.short_description = 'Preço'

    def get_price_formact_promo(self):
        return utils.formact_price(self.price_marketing_promotion)
    get_price_formact_promo.short_description = 'Preço promo'

    @staticmethod
    def resize_image(img, new_width):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(img_full_path,optimize=True,quality=80)


    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}'
            self.slug = slug

        super().save(*args, **kwargs)
        max_image_size = 800

        if self.image:
            self.resize_image(self.image, max_image_size)

    def __str__(self) -> str:
        return self.name
    

class Variation(models.Model):
    class Meta:
        verbose_name = 'Variation'
        verbose_name_plural = 'Variations'

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, null=True)
    price = models.FloatField()
    price_promotion = models.FloatField(default=0)
    stock = models.PositiveIntegerField(default=1)

    def __str__(self) -> str:
        return self.name or self.product.name
    
    

avancado/django/3_P_E_Comerce/app/Product/forms.py
from django.forms.models import BaseInlineFormSet

class VariationRequired(BaseInlineFormSet):
    def _construct_form(self, i, **kwargs):
        form = super(VariationRequired, self)._construct_form(i, **kwargs)
        form.empty_permitted = False
        return form

avancado/django/3_P_E_Comerce/app/Product/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from django.db.models import Q
from . import models
from Profile.models import Profile

class ListProduct(ListView):
    model = models.Product
    template_name = 'Product/_list.html'
    context_object_name = 'products'
    paginate_by = 10
    ordering = ['-id']

class GetProduct(ListProduct):
    def get_queryset(self, *args, **kwargs):
        term = self.request.GET.get('termo') or self.request.session['termo']
        qs = super().get_queryset(*args, **kwargs)

        if not term:
            return qs
        
        self.request.session['termo'] = term
        qs = qs.filter(
            Q(name__icontains=term) |
            Q(description_short__icontains=term) |
            Q(description_long__icontains=term))
        
        self.request.session.save()
        return qs
        
class DetailProduct(DetailView):
    model = models.Product
    template_name = 'Product/_details.html'
    context_object_name = 'Product'
    slug_url_kwarg = 'slug'


class AddToCar(View):
    def get(self, *args, **kwargs):
        
        http_referer = self.request.META.get('HTTP_REFERER', reverse('Product:list'))
        variation_id = self.request.GET.get('vid')
        
        if not variation_id:
            messages.error(self.request, 'Produto não existe')
            return redirect(http_referer)
        
        variation = get_object_or_404(models.Variation, id=variation_id)
       
        variation_stock = variation.stock
        product = variation.product

        product_id = product.id
        product_name = product.name
        variation_name = variation.name or ''
        price_unt = variation.price
        price_unt_promo = variation.price_promotion
        slug = product.slug
        image = product.image.name if product.image else ''

        if variation.stock < 1:
            messages.error(self.request, 'Estoque insuficiente')
            return redirect(http_referer)
        
        if 'car' not in self.request.session:
            self.request.session['car'] = {}
            self.request.session.save()

        car = self.request.session['car']

        if variation_id in car:
            amount_car = car[variation_id]['amount'] + 1
            if variation_stock < amount_car:
                messages.warning(self.request,f'Estoque insuficiente para {amount_car}x no '
                    f'produto "{product_name}". Adicionamos {variation_stock}x '
                    f'no seu carrinho.')
                amount_car = variation_stock

            car[variation_id]['amount'] = amount_car
            car[variation_id]['price_amount'] = price_unt * amount_car
            car[variation_id]['price_amount_promo'] = price_unt_promo * amount_car

        else:
            car[variation_id] = {
                'product_id': product_id,
                'product_name': product_name,
                'variation_name': variation_name,
                'variation_id': variation_id,
                'price_unt': price_unt,
                'price_unt_promo': price_unt_promo,
                'price_amount': price_unt,
                'price_amount_promo': price_unt_promo,
                'amount': 1,
                'slug': slug,
                'image': image
            }

        self.request.session.save()

        messages.success(self.request, f'Produto {product_name} {variation_name} adicionado ao seu '
            f'carrinho {car[variation_id]["amount"]}x.')
        
        return redirect(http_referer)

class RemoveToCar(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get('HTTP_REFERER', reverse('Product:list'))

        variation_id = self.request.GET.get('vid')

        if not variation_id:
            return redirect(http_referer)
        
        if not self.request.session.get('car'):
            return redirect(http_referer)
        
        if variation_id not in self.request.session['car']:
            return redirect(http_referer)
        
        car = self.request.session['car'][variation_id]

        messages.success(self.request, f'Produto {car["product_name"]} {car["variation_name"]} '
            f'removido do seu carrinho.')
        
        del self.request.session['car'][variation_id]
        self.request.session.save()
        return redirect(http_referer)
    
class Car(View):
    def get(self, *args, **kwargs):
        context = {
            'car': self.request.session.get('car', {})
        }
        return render(self.request, 'Product/_car.html', context)
    
    
class ResumeToShoop(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('Profile:create')
        
        profile = Profile.objects.filter(user=self.request.user).exists()
        
        if not profile:
            messages.error(self.request,'Usuário sem perfil')
            return redirect('Profile:create')
        
        if not self.request.session.get('car'):
            messages.error(self.request, 'Carrinho vazio')
            return redirect('Product:list')
        
        context = {
            'user': self.request.user, 
            'car': self.request.session['car']
        }

        return render(self.request, 'Product/_resumeshoop.html', context)
    

avancado/django/3_P_E_Comerce/app/Product/templates/Product/_car.html
{% extends 'base.html' %}

{% block title %}Carrinho | {% endblock %}
{% load _filter %}
{% block content %}

{% if car %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho de compras</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>
            {% include 'partials/_car.html' %}
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>{{ car | cart_totals | formact_price  }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">

            {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'Product:resumetoshoop' %}">
                Comprar
            </a>
            {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'Profile:create' %}">
                Entrar ou cadastrar e comprar
            </a>
            {% endif %}
        </div>
    </div>

{% else %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho vazio</h3>
            <p class="lead">Não há produtos no seu carrinho.</p>
        </div>
    </div>

{% endif %}
{% endblock %}

avancado/django/3_P_E_Comerce/app/Product/templates/Product/_details.html
{% extends 'base.html' %}
{% block title %} {{ Product.name }} | {% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-lg">
            <div class="row no-gutters">
                <div class="col-lg-12">
                    {% if Product.image %}
                        <img class="img-fluid" src="{{ Product.image.url }}">
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg">
            <div class="mt-4 mt-lg-0">
                <h1 class="h2">{{ Product.name }}</h1>
                <p class="lead">{{ Product.description_short }}</p>
                <p class="lead">
                    {% if Product.price_marketing_promotion %}
                    <span id="variation-preco-promocional" class="lead product-price">
                        {{ Product.price_marketing_promotion}}
                    </span>
                    <span id="variation-preco" class="lead product-old-price text-muted">
                        {{ Product.price_marketing}}
                    </span>
                    {% else %}
                    <span id="variation-preco" class="lead product-price">
                        {{ Product.price_marketing}}
                    </span>
                    {% endif %}
                </p>

                <form action="{% url 'Product:addtocar' %}" id="form-add-to-cart">
                    <div class="form-group">
                        <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                            {% for variacao in Product.variation_set.all %}
                                {% if variacao.price_promotion %}
                                    <option data-preco="{{ variacao.price }}"
                                        data-preco-promocional="{{ variacao.price_promotion }}"
                                        value="{{ variacao.id }}">
                                        {% if variacao.nome %}
                                            {{ variacao.nome }}
                                        {% else %}
                                            {{ variacao }}
                                        {% endif %}
                                    </option>
                                {% else %}
                                    <option data-preco="{{ variacao.price }}" value="{{ variacao.id }}">
                                        {% if variacao.name %}
                                            {{ variacao.name }}
                                        {% else %}
                                            {{ variacao }}
                                        {% endif %}
                                </option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="text-left">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Adicionar ao carrinho
                        </button>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="mt-5 mb-5">
                <h2 class="text-center">{{ Product.name }}</h2>
                {{ Product.description_long | linebreaks }}
            </div>
        </div>
    </div>

{% endblock %}

avancado/django/3_P_E_Comerce/app/Product/templates/Product/_list.html
{% extends 'base.html' %}
{% block title %} Produtos | {% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in products %}

                <div class="card">

                    {% if produto.image %}
                        <a href="{% url 'Product:detail' produto.slug %}">
                            <img class="card-img-top" src="{{ produto.image.url }}" alt="{{ produto.name }}">
                        </a>
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ produto.name }}</h5>
                        <p class="card-text">{{ produto.description_short }}</p>
                        <div class="container product-price-block text-center">

                            {% if produto.price_marketing_promotion %}
                            <span class="product-price">
                                {{ produto.price_marketing_promotion }}
                            </span>
                            <span class="product-old-price text-muted">
                                {{ produto.price_marketing }}
                            </span>
                            {% else %}
                            <span class="product-price">
                                {{ produto.price_marketing }}
                            </span>
                            {% endif %}

                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-top-light-custom text-center">
                        <a href="{% url 'Product:detail' produto.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Comprar
                        </a>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
    </div>
</div>

{% endblock %}

avancado/django/3_P_E_Comerce/app/Product/templates/Product/_resumeshoop.html
{% extends 'base.html' %}
{% load _filter %}

{% block title %}Resumo da compra | {% endblock %}

{% block content %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'Profile:create' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ user.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ user.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ user.Profile.age }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ user.Profile.date_of_birth }}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ user.Profile.cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ user.email }}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url 'Profile:create' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{ user.profile.address }}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{ user.profile.number }}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{ user.profile.complement }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ user.profile.neighborhood }}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{ user.profile.city }}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{ user.profile.state }}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{ user.profile.cep }}</dd>
        </dl>
    </div>
</div>



<div class="row mt-3">
    <div class="col">
        <h3>Resumo do carrinho</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include 'partials/_car.html' %}
    </div>

</div>
<div class="row mt-3">
    <div class="col">
        <p class="lead text-center"><span class="font-weight-bold">Total do carrinho:</span>
            {{ car |cart_totals }}</p>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'Order:saveorder' %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>


{% endblock %}